# Generated by Django 5.2.14 on 2026-05-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailNotificationPreference",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediately"),
                            ("10m", "Every 10 minutes"),
                            ("30m", "Every 30 minutes"),
                            ("1h", "Every hour"),
                            ("daily", "Daily"),
                            ("off", "Off"),
                        ],
                        default="off",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("next_send_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["user_id"],
            },
        ),
        migrations.CreateModel(
            name="EmailMatchDelivery",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reddit_item_id", models.CharField(max_length=255)),
                ("sent_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="emailmatchdelivery",
            constraint=models.UniqueConstraint(
                fields=("user", "reddit_item_id"),
                name="unique_email_match_delivery_per_user_item",
            ),
        ),
    ]
