# Generated by Django 5.2.14 on 2026-05-21 02:31

from datetime import timedelta

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


CADENCE_INTERVALS = {
    '10m': timedelta(minutes=10),
    '30m': timedelta(minutes=30),
    '1h': timedelta(hours=1),
    'daily': timedelta(days=1),
}


def migrate_account_cadences(apps, schema_editor):
    EmailNotificationPreference = apps.get_model('alerts', 'EmailNotificationPreference')
    EmailNotificationSchedule = apps.get_model('alerts', 'EmailNotificationSchedule')
    Monitor = apps.get_model('tracking', 'Monitor')

    now = timezone.now()
    for preference in EmailNotificationPreference.objects.exclude(cadence='off'):
        Monitor.objects.filter(
            user_id=preference.user_id,
            notification_cadence='off',
        ).update(notification_cadence=preference.cadence)

        interval = CADENCE_INTERVALS.get(preference.cadence)
        if interval is None:
            continue

        EmailNotificationSchedule.objects.get_or_create(
            user_id=preference.user_id,
            cadence=preference.cadence,
            defaults={
                'next_send_at': preference.next_send_at or now + interval,
                'last_sent_at': preference.last_sent_at,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('tracking', '0003_add_notification_cadence_to_monitor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.CharField(choices=[('immediate', 'Immediately'), ('10m', 'Every 10 minutes'), ('30m', 'Every 30 minutes'), ('1h', 'Every hour'), ('daily', 'Daily'), ('off', 'Off')], max_length=16)),
                ('next_send_at', models.DateTimeField(db_index=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'cadence'],
                'constraints': [models.UniqueConstraint(fields=('user', 'cadence'), name='unique_email_schedule_per_user_cadence')],
            },
        ),
        migrations.RunPython(migrate_account_cadences, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='emailnotificationpreference',
            name='cadence',
        ),
        migrations.RemoveField(
            model_name='emailnotificationpreference',
            name='next_send_at',
        ),
    ]
