# Generated by Django 5.2.14 on 2026-05-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_match_id_alter_monitor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='notification_cadence',
            field=models.CharField(choices=[('immediate', 'Immediately'), ('10m', 'Every 10 minutes'), ('30m', 'Every 30 minutes'), ('1h', 'Every hour'), ('daily', 'Daily'), ('off', 'Off')], default='30m', max_length=16),
        ),
    ]
