# Generated by Django 5.2.14 on 2026-05-30 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_matchretentionpreference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDismissal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_item_id', models.CharField(max_length=255)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dismissed_at'],
                'indexes': [models.Index(fields=['user', 'reddit_item_id'], name='tracking_dismissal_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'reddit_item_id'), name='unique_match_dismissal_per_user_item')],
            },
        ),
    ]
