# Generated by Codex on 2026-05-06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("reddit", "0002_alter_reddititem_id_alter_subredditfetchstate_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="subredditfetchstate",
            name="kind",
            field=models.CharField(
                choices=[
                    ("post_search", "Post search"),
                    ("comment_search", "Comment search"),
                    ("post_stream", "Post stream"),
                    ("comment_stream", "Comment stream"),
                ],
                default="post_stream",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subredditfetchstate",
            name="format",
            field=models.CharField(
                choices=[("rss", "RSS"), ("json", "JSON")],
                default="rss",
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subredditfetchstate",
            name="query_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subredditfetchstate",
            name="next_fetch_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="subredditfetchstate",
            name="consecutive_failures",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subredditfetchstate",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="subredditfetchstate",
            name="subreddit",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelOptions(
            name="subredditfetchstate",
            options={"ordering": ["subreddit", "kind", "format", "query_fingerprint"]},
        ),
        migrations.AddIndex(
            model_name="subredditfetchstate",
            index=models.Index(
                fields=["kind", "format", "subreddit"],
                name="reddit_subr_kind_eb52e6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="subredditfetchstate",
            constraint=models.UniqueConstraint(
                fields=("kind", "format", "subreddit", "query_fingerprint"),
                name="unique_reddit_fetch_state_feed",
            ),
        ),
    ]
